# -*- coding: utf-8 -*-
"""Codigo_MVP_Matchday

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10HbU1kZl20gJgK8-MBIZeuppj6aZRfCV
"""

import streamlit as st

with st.container():
  url = 'https://www.youtube.com/watch?v=JK14AYu-wOs'
  st.video(url)
  lista_comentarios = ['Irado', 'Muito legal']
  title = st.text_input('Deixe seu comentário (se quiser se identificar, coloque seu nome entre () no início)','')
  lista_comentarios.append(title)
  expander = st.expander('Comentários')
  for comentario in lista_comentarios:
    expander.write(comentario)

  
    
  
  
  
